{% set name = "search-engine-parser" %}
{% set version = "0.6.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/search-engine-parser-{{ version }}.tar.gz
  sha256: 26a28b9dee1ccf5f5c228dce697cc3c0dbe38cd68062c72d68da9a9ef434838f

build:
  number: 1
  noarch: python
  entry_points:
    - pysearch=search_engine_parser.core.cli:runner
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - aiohttp ==3.7.4
    - beautifulsoup4 ==4.9.1
    - fake-useragent ==0.1.11
    - lxml ==4.6.5
    - python >={{ python_min }}
    - blessed

test:
  imports:
    - search_engine_parser
    - search_engine_parser.core
  commands:
    - pip check
    - pysearch --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bisoncorps/search-engine-parser
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Lightweight package to query popular search engines and scrape for result titles, links and descriptions
  description: |
    search-engine-parser is a package that lets you query popular
    search engines and scrape for result titles, links, descriptions and
    more. It aims to scrape the widest range of search engines.
  doc_url: https://search-engine-parser.readthedocs.io/
  dev_url: https://github.com/bisoncorps/search-engine-parser

extra:
  recipe-maintainers:
    - jan-janssen
